export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const LISTFILES_SUCCESS = "LISTFILES_SUCCESS";
export const LISTFILES_FAILURE = "LISTFILES_FAILURE";
